# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rik Lubbers, MSc
title: Research Master student in Clinical and Psychosocial Epidemiology, Health Systems and Prevention
email: rik.lubbers@outlook.com
phone: +31 6 346 268 94
website: www.RikLubbers.github.io/MyWebsite

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  RikLubbers
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: rik-lubbers
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-2772-1524

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rik and thank you for your interest in my website. Currently I am a student at the University of Groningen where I am pursuing my second master degree in Clinical and Psychosocial Epidemiolgy, Health systems and prevention.
  
  My research interests lie mostly in Low- and Middle-Income countries focusing on maternal and neonatal health and pharmaceutical systems. However, I must say that my interests are broad and yet carved into stone. 

  As of now, my best skills include being <mark>open-minded</mark>, <mark> curious </mark> and <mark>interested</mark> in learning new skills and topics, such as creating a resume using github or my recent endeavours in using RStudio.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak
        title: Physical Healthcare Facility Access and Malnutrition in Children Under-5 in Uganda (forthcoming)
        link: Link to complete pdf file
        # link_text: Link to document
        quote: >
          Estimating the impact of physical healthcare facility access on malnutrition rates in children under-5 in Uganda 
        description: | # this will include new lines to allow paragraphs
          Worldwide, around 230 million children suffer from malnutrition. Malnutrition comprises of three conditions: stunting, wasting and underweight. In Uganda, 29% of all children under-5 years are stunted, 3.5% are wasted and 11% are underweight. Malnutrition is a preventable and treatable condition with a multifaceted range of determinants. Two of the respective immediate and underlying determinants of malnutrition include adequate care and services. These determinants comprise of the essential services provided by the healthcare system to prevent and treat malnutrition. 
          
            Access to healthcare has been deemed an important determinant in the prevention and treatment of malnutrition. Evidence measuring the impact of physical accessibility on malnutrition is limited with previous studies on other health outcomes and practices leaning towards a negative association. However, discrepancies exist. Currently the impact of physical accessibility on malnutrition in children under-5 in Uganda is not known. Therefore, the question of our project is: what the impact of travel time to the nearest healthcare facility on malnutrition in children under-5 years in Uganda?
          
          
            Within this program I have had the chance to develop new skills in <mark>R</mark> and <mark>ArcGIS PRO</mark> including <mark>geospatial analysis techniques</mark>. This project has been a great oppertunity to broaden my skills in <mark>public health</mark>, <mark>epidemiology</mark> as well as <mark>database & project management</mark>.
          
          ![Example image from project](images/picture1.jpg "ArcGIS picture 1")
          ![Example image from project](images/picture2.jpg "ArcGIS picture 2")
  
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Erasmus school of Health Policy and Management
        link: https://www.eur.nl/en/eshpm
        # link_text: https://www.eur.nl/en/eshpm
        sub_title: Research Assistant
        caption: October 2021 - June 2022
        quote: >
          Being part of a multidisciplinary international team trying to gather the knowledge on substandard and falsified medicine. 
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Groningen
        caption: 2021 - 2023
        sub_title: MSc in Clinical and Psychosocial Epidemiology, Health Systems and Prevention
        quote: >
          A renowned public research university of more than 30,000 students in the city of Groningen in the Netherlands. Founded in 1614, the university is the second oldest in the country and one of the most traditional and prestigious universities in the Netherlands.
        description: | # this will include new lines to allow paragraphs
          This master aims at combining cutting-edge interdisciplinary research with practical policy questions, aiming to solve complex public health problems related to societal issues like an ageing population, increasing levels of chronic diseases, widening health inequalities, migration and urbanization. You learn to tackle issues like these from various academic disciplines, as you are taught and supervised by experts in economics, spatial sciences, psychology, sociology, and medicine.
          
          During my time at University of Groningen I learnt most of my key skills such as teamwork and working to tight deadlines. I thouroughly enjoyed my time at university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a basketball player of the *Groene Uilen-Moestasj basketball association*.
                 
      - layout: left
        title: Vrije Universiteit Amsterdam 
        caption: 2020 - 2021
        sub_title: MSc in International Public Health
        quote: >
          A renowned public research university founded in 1880. The university consistently ranks among the top 150 universities in the world by prominent international ranking tables.
        description: | # this will include new lines to allow paragraphs
          This master is aimed at mastering knowledge and skills in analyzing complex health or health care problems and in contributing to the development and implementation of interventions or programs to solve these problems.
       
          I spent my free time as a co-founder and podcaster of the widely published weekly podcast *"onthaasten"*. The podcast is discontinued now but I look back joyfully on the discussion we've had on all topics related to slowed down intentful life.          
      - layout: left
        #title: Vrije Universiteit Amsterdam 
        caption: 2019 - 2020
        sub_title: Pre-master Health Sciences
        description: | # this will include new lines to allow paragraphs
          Coming from an University of Applied Sciences I had to follow a pre-master to be eligible for the master program in International Public Health.           
      - layout: left
        title: Hanze University Groningen
        caption: 2015 - 2019
        sub_title: Bsc(hons) in Nursing
        quote: >
          The largest technical & vocational university in the northern Netherlands.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in research in health systems and low- and middle-income countries, my other interest and hobbies are:
      - Playing basketball
      - Reading (fiction and non-fiction), link to [GoodReads](https://www.goodreads.com/user/show/46131131-rik-lubbers)
      - Zen Buddhism 
      - Walks in nature
      - Watching documentaries 

      [Link](link here) to PDF resume

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
